remote_theme: pages-themes/modernist@v0.2.0
title: DevDogs
description: Just note and published

# Enable required plugins (GitHub Pages supported)
plugins:
  - jekyll-remote-theme
  - jekyll-readme-index

# Treat README.md as the site index
readme_index:
  enabled: true

# Exclude items from the site build
exclude:
  - node_modules/
  - vendor/
  - Gemfile*
  - package*.json
  - README*.md.tmp